name: use my action
on: push
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: 'main'
    - name: My first step
    - run: echo "ovidi"

