name: use my action
on: [push]
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: octocat/say-hello@v1
        with: 
          name: OctoCatnj
